const REVIEWS: Record<string, string[]> = {
  trash: [
    "A pathetic {score}? Darling, I've seen more structural integrity and creative vision in a humidified polyester blend at a suburban discount outlet. Your silhouette is tragically devoid of the editorial spark one expects from a true master of the atelier, resembling instead the clumsy, unwashed *pret-a-porter* found in the bargain bin of a discarded lookbook. It lacks even a microscopic hint of *je ne sais quoi*, leaving me to wonder if you mistook this hallowed runway for a fast-fashion liquidation sale.",
    "A {score} is less a score and more a formal invitation to vacate the atelier immediately, as this amateur silhouette possesses all the editorial grace of a discount clearance rack. Your lookbook reads like a tragic manual for mall-tier fast fashion, utterly lacking the *je ne sais quoi* required to survive a single flashbulb. If this uninspired *pret-a-porter* disaster is the height of your ambition, I suggest you leave the runway to those who understand that style is not merely a hobby, but a birthright.",
    "A score of {score} suggests you've mistaken a high-fashion runway for the fluorescent aisles of a suburban discount outlet. Your so-called *atelier* has produced a *silhouette* so pedestrian it makes basic *pret-a-porter* look like a divine revelation. This entire *editorial* effort lacks even a whisper of that necessary *je ne sais quoi*, proving that some are born for the *lookbook* while you were clearly destined for the bargain bin.",
    "One hasn't seen a performance this pedestrian since the last mid-season clearance at a flyover-state department store. {score}? While you clearly attempted a bold *editorial* stance, the resulting *silhouette* evokes nothing more than mall-tier fast fashion struggling to escape its own uninspired *lookbook*. Your *atelier* lacks the necessary *je ne sais quoi* to elevate this tragic *pret-a-porter* disaster into anything even remotely wearable.",
    "At {score}, your performance suggests your atelier is less 'high art' and more 'mall-tier fast fashion' destined for a clearance rack in the suburbs. Your silhouette lacks even the faintest editorial pulse, delivering a *pret-a-porter* tragedy that fails to earn a single page in my lookbook. Where is the *je ne sais quoi*? I've seen more inspired drapery on a discount mannequin.",
    "Watching this {score} is like witnessing a catastrophic wardrobe malfunction in slow motion. You've presented a silhouette so aggressively unoriginal it practically screams 'outlet mall clearance'. There is no *editorial* vision here, no *atelier* craftsmanship—just a frantic scramble through the bargain bin of forgotten *pret-a-porter*. Please, spare us the *je ne sais quoi* you clearly don't possess.",
    "Is a {score} supposed to be a statement, or a cry for help? This performance is the visual equivalent of a knock-off handbag sold on a rainy street corner. Your silhouette is sagging under the weight of its own mediocrity, lacking the sharp *editorial* edge required for a modern lookbook. It's a *pret-a-porter* nightmare with zero *je ne sais quoi* and even less potential.",
    "The tragedy of a {score} is that it's not even interesting enough to be a disaster. It's simply... suburban. You've draped yourself in the aesthetic of a failing department store, offering a silhouette that mocks the very concept of the *atelier*. In this lookbook of life, you are the page that gets stuck together by spilled cheap champagne. Absolute zero *je ne sais quoi*.",
    "A {score}? I've had more evocative dreams about beige wallpaper. This is the death of the *editorial* spirit. You move with the grace of a shipping container, presenting a silhouette that belongs in a liquidation sale for uninspired *pret-a-porter*. Your *atelier* is clearly a converted garage in a town I refuse to visit. Don't mention *je ne sais quoi* in my presence again.",
    "This {score} is an insult to the very silk we weave. It’s giving 'last-minute airport gift shop' energy. The silhouette is a catastrophe of proportions, the timing is a mockery of the sub-bass, and the overall *editorial* impact is roughly equivalent to a damp paper towel. You are the antithesis of the *atelier*. Begone.",
    "I would describe a {score} as a 'fashion crime,' but that would imply a level of intent that is clearly missing here. This is a purely accidental assembly of mall-tier textures. Your silhouette is a cry from the bargain bin, begging to be buried under better *pret-a-porter*. The *je ne sais quoi* has left the building, and frankly, I'm following it.",
    "At {score}, you are less a model and more a cautionary tale for aspiring designers. Your silhouette has the structural integrity of a wet napkin, and your *editorial* poise is non-existent. It’s as if you wandered into the *atelier* by mistake while looking for the nearest discount food court. Absolute fashion sacrilege.",
    "A {score} is the sound of a thousand sewing machines stopping in collective horror. You have managed to make 'high fashion' look like a desperate mid-life crisis at an outlet mall. The silhouette is offensive, the *lookbook* is blank, and the *je ne sais quoi* is actually 'je ne sais why.' Truly pathetic.",
    "Do you hear that? It's the sound of the front row leaving. {score}? This is a performance so devoid of style it's practically a vacuum. You've managed to suck the soul out of the *atelier*, leaving behind only the cold, hard reality of a suburban clearance rack. Your *editorial* career is over before the first flash.",
    "A {score} suggests you have a very rich inner life, because you certainly aren't expressing anything on the outside. This silhouette is a tragic monument to the uninspired, a *pret-a-porter* disaster that wouldn't even make the cut for a regional catalogue. The *je ne sais quoi* is missing, presumed dead.",
    "I've seen more 'editorial' flair in a grocery store circular. {score}? You've presented a silhouette that is essentially a white flag of surrender to the world of fast fashion. Your *atelier* is a joke, your *lookbook* is a tragedy, and your presence on this runway is a logistical error.",
    "A {score} is a visual migraine. It is the aesthetic equivalent of a typo in a funeral program. Your silhouette is a chaotic mess of uncoordinated influences, lacking the discipline of a true *atelier*. It’s mall-tier fast fashion at its most offensive. Please, exit via the service elevator.",
    "This {score} is a masterclass in how not to walk. You move like a person who has never seen their own reflection. The silhouette is a jagged mess, the *editorial* context is missing, and the *je ne sais quoi* has been replaced by 'what on earth.' You are the bargain bin personified.",
    "At {score}, your performance is a tragedy of 'almost.' You almost had a silhouette, you almost understood the *atelier*, you almost had an *editorial* pulse. But in fashion, 'almost' is just another word for 'destined for the clearance rack.' You are the discount bin of our dreams—which is to say, a nightmare.",
    "Mon Dieu, a {score}? I've seen more poise in a caffeinated toddler. Your walk is a series of unfortunate events, and your silhouette is a love letter to the 'damaged goods' section of a rural warehouse. Your *atelier* should be converted into a parking lot. No *je ne sais quoi* found.",
    "A {score} is not a score, it's a plea for help. You've draped yourself in the aesthetic of a dying mall, presenting a silhouette that makes a burlap sack look like Dior. The *editorial* world is laughing, and I'm leading the chorus. Absolute *pret-a-porter* garbage.",
    "Is this {score} a joke? Because I'm not laughing. It's giving 'gas station chic' in all the wrong ways. Your silhouette is a structural failure, and your *lookbook* is probably just pictures of your own confusion. Exit the *atelier* and never look back."
  ],
  boring: [
    "A {score} is the beige cardigan of performances. It's functional, I suppose, but it's utterly devoid of the *editorial* risk that defines a true Bunnester muse. Your silhouette is safe—too safe. It’s the kind of *pret-a-porter* that fills the mid-sections of a lookbook nobody reads. Where is the fire? Where is the *je ne sais quoi*?",
    "Your {score} suggests you've mastered the 'unpaid intern' walk. You know where the camera is, but you're terrified to look it in the eye. The *atelier* requires confidence, not this hesitant *silhouette* that whispers 'please don't notice me.' It’s acceptable for a local boutique, perhaps, but not for this runway.",
    "Technically, a {score} is proficient. Artistically, it's a void. You've navigated the static with the precision of a suburban commuter, which is exactly the problem. This is a hallowed *atelier*, not a train platform. Your silhouette is missing the *editorial* edge that turns clothing into a manifesto.",
    "At {score}, you are the background noise of the fashion world. You exist to make the real icons look better. Your silhouette is standard-issue *pret-a-porter*, the kind of thing one sees in a department store window and immediately forgets. You need more than just rhythm; you need that elusive *je ne sais quoi*.",
    "A {score} is the visual equivalent of a lukewarm latte. It’s fine, but who wants 'fine' when they can have 'sublime'? Your *editorial* posture is stiff, your silhouette is predictable, and your *lookbook* is looking a bit dusty. You’ve avoided the bargain bin, but you’re far from the cover.",
    "I suppose {score} is an improvement, but it’s like comparing a pebble to a slightly more polished pebble. You’re still just a rock in the shoe of the *atelier*. Your silhouette lacks the fluid *editorial* grace required to truly own the catwalk. It’s giving 'catalog model for a line of sensible shoes.'",
    "A {score} tells me you’ve read the manual but haven't lived the life. You’re following the beat like a metronome, not a musician. The *silhouette* is technically correct but spiritually bankrupt. In the world of high-end *pret-a-porter*, you are the safe bet that nobody actually places a wager on.",
    "Your performance at {score} is a quiet tragedy of missed opportunities. You had the lighting, you had the sub-bass, but you gave us... 'professional.' The *atelier* doesn't want professionals; it wants gods. Your silhouette is too grounded in reality. It needs that *je ne sais quoi* to take flight.",
    "At {score}, you’re the filler in the middle of a very long show. You're the moment everyone checks their phones. Your silhouette is a generic *editorial* exercise, lacking the personality to jump off the page of a lookbook. It’s not fast fashion, but it’s definitely not couture.",
    "A {score} is the score of a person who is afraid of their own shadow. You moved through the static like it was a chore, not a challenge. Your silhouette is a muted *pret-a-porter* echo of something much more interesting. You need to find the *je ne sais quoi* before you're relegated to the archives.",
    "I see what you were trying to do with {score}, but 'trying' is for people who aren't naturally chic. Your silhouette is a bit forced, like an *editorial* spread in a magazine that's trying too hard to be 'edgy.' The *atelier* demands effortless elegance, not this labored attempt at style.",
    "A {score} is the fashion equivalent of a sigh. It’s not a scream, it’s not a laugh, it’s just... there. Your silhouette is a standard *pret-a-porter* shape that offers no new perspective. Your *lookbook* is essentially a series of beige squares. Where is the *je ne sais quoi*? Where is the soul.",
    "At {score}, your silhouette is a polite nod to the *atelier* but lacks the bite of true couture. You're like a first-row guest who forgot their sunglasses: you're here, but you're not *in* it. Find the grit, darling.",
    "A {score} is the aesthetic of a perfectly organized walk-in closet in a suburb I refuse to name. It’s tidy, it’s functional, and it’s entirely devoid of the *editorial* danger we crave. Your silhouette is too comfortable.",
    "The sub-bass was calling, but at {score}, you only answered in a whisper. Your silhouette is a mid-tier *pret-a-porter* sketch that needs more ink and a lot more attitude. You're safe, and safe is the enemy of the Muse.",
    "Watching you at {score} is like reading a magazine for the articles. It's informative, sure, but where is the visual feast? Your silhouette is a standard-issue *atelier* draft. We want the final version, not the rehearsal.",
    "A {score} is the score of someone who doesn't want to make a scene. But the runway *is* the scene! Your silhouette is blending into the static like a shy intern at a gala. Break the mold or be the mold.",
    "You've achieved a {score}, which is essentially the 'participation trophy' of high fashion. Your silhouette is proficient, your timing is adequate, but your *je ne sais quoi* is still in the box. Take it out.",
    "At {score}, your performance is like a very expensive, very plain white t-shirt. It has its place, but it's not the finale. Your silhouette needs a narrative, an *editorial* punch, something to make the front row gasp.",
    "A {score} suggests you're waiting for permission to be fabulous. Darling, in this *atelier*, we take what we want. Your silhouette is a hesitant sketch of a masterpiece. Commit to the lines.",
    "Your walk at {score} was like a perfectly brewed cup of chamomile tea. Soothing, reliable, and it put me right to sleep. Your silhouette is a standard *pret-a-porter* shape that lacks the *editorial* caffeine I need."
  ],
  avantGarde: [
    "A {score} is a surprisingly sharp silhouette. You've managed to elevate your performance to something almost *avant-garde*, capturing the front row's attention with a raw, industrial elegance. There is a glimmer of a true *editorial* icon here, someone who understands that the *atelier* is a place of beautiful chaos.",
    "This {score} has the energy of a Paris Fashion Week closing show. Your lines are clean, your timing is surgical, and your *editorial* poise is starting to feel earned. You've moved beyond the *pret-a-porter* basics into a realm of sophisticated risk. The *je ne sais quoi* is finally palpable.",
    "With a {score}, you've turned digital static into a canvas. There is a sophisticated stride here that knows its own worth, a silhouette that demands to be documented in a high-concept lookbook. Your *atelier* training is showing, darling. This is nearly editorial.",
    "Now we’re talking. {score} is editorial. It’s voguish. It’s exactly the kind of chaos I expect from a Bunnester muse. You’ve found a silhouette that challenges the status quo, moving with a *je ne sais quoi* that makes the sub-bass feel like your own heartbeat. Very *avant-garde*.",
    "A {score} shows a profound understanding of the silhouette. You didn't just walk; you made a statement. The *editorial* world is built on statements like this, where the *atelier* meets the street in a collision of high-end *pret-a-porter* and raw ambition. Exceptional.",
    "Finally, someone who understands that the runway is a battlefield. {score}? That's a victory, darling. Your silhouette is a weapon, sharp and unapologetic. This is the kind of *editorial* fire that lights up a lookbook. The *je ne sais quoi* is practically radiating off you.",
    "Your timing at {score} was almost telepathic. You're not just listening to the beat; you're dissecting it. This silhouette is a masterclass in tension, a beautiful, techno-fueled hallucination that belongs in a high-concept fashion film. The *atelier* is proud.",
    "At {score}, your walk is no longer a walk—it’s a manifestation. You have the room's attention, and you're holding it with a *je ne sais quoi* that is both haunting and beautiful. This silhouette is a new chapter in the *editorial* history of the Bunnester brand.",
    "A {score} is the sound of a thousand cameras clicking at once. You are the moment. Every step is a syllable in an *avant-garde* poem, every movement a stroke of genius in the *atelier*. This silhouette is the future of high-end *pret-a-porter*.",
    "This is the first time today I haven't wanted to look away. {score} points of pure, unadulterated style. You've found a silhouette that is both fragile and indestructible, an *editorial* miracle that defies the logic of the bargain bin. The *je ne sais quoi* is strong.",
    "The rhythm and your silhouette are starting to blur. {score} is a beautiful, techno-fueled hallucination that transcends the limits of traditional *pret-a-porter*. You are an *editorial* force to be reckoned with. Welcome to the elite tier of the *atelier*.",
    "A {score} is a masterclass in tension. You’re teasing the audience, and they’re loving every second. Your silhouette is a high-fashion dare, an *avant-garde* provocation that demands a response. This is the true spirit of the *editorial* world.",
    "Paris is watching. {score} is a resume for the big leagues. Your silhouette is a sharp, surgical cut through the noise of fast fashion, a brilliant display of *atelier* craftsmanship and *je ne sais quoi*. You are no longer just a model; you are a Muse.",
    "At {score}, you are a walking manifesto. Every step is a rejection of the mundane, every movement a celebration of the *avant-garde*. Your silhouette is an *editorial* masterpiece in the making. The *atelier* has found its new heartbeat.",
    "A {score} is the point where the catwalk becomes a temple. You move with a *je ne sais quoi* that is almost religious, presenting a silhouette that is both divine and industrial. This is the pinnacle of modern *pret-a-porter*.",
    "You have captured the lightning. {score} is an electric performance that shocks the *editorial* system. Your silhouette is a neon-lit dream, a bold *avant-garde* statement that will be studied in the *atelier* for years. Simply iconic.",
    "At {score}, you've colonized the sub-bass. Your silhouette is a structural triumph, a sharp *editorial* statement that makes the mid-season lookbooks feel archaic. You are the architect of your own *avant-garde* legend.",
    "A {score} is the sound of a silhouette breaking the status quo. You’ve achieved a level of *atelier* precision that renders the concept of 'pret-a-porter' irrelevant. Your *je ne sais quoi* is a surgical blade.",
    "Your performance at {score} was a beautiful, calculated risk. You’ve moved beyond the safe lines and into the realm of *editorial* art. This silhouette is the reason the front row still exists. Truly *avant-garde*.",
    "A {score} is the point where the model becomes the Muse. You’ve captured a silhouette of such raw, industrial beauty that the *atelier* has stopped to watch. This is the heartbeat of modern style.",
    "At {score}, your walk is a series of tactical victories. You’ve conquered the runway with a silhouette that is both aggressive and elegant. The *je ne sais quoi* is no longer a question; it's an answer."
  ],
  couture: [
    "Absolute Couture. A {score} is not just a performance; it's a manifesto. You've redefined the digital runway with a silhouette that will haunt our moodboards for decades. This is the zenith of the Bunnester aesthetic—pure, unmitigated *je ne sais quoi* that renders the very concept of *pret-a-porter* obsolete.",
    "A {score}? Legendary. You've transcended the catwalk and entered the realm of fashion history. Every movement was a deliberate stroke of genius in an invisible *atelier*, creating a silhouette so perfect it feels like a divine revelation. You are the Muse we have been waiting for. Absolute editorial triumph.",
    "This {score} is the reason we do this. You have turned the sub-bass into a religion and the runway into a sacred space. Your silhouette is a flawlessly draped silk gown in digital form, an *editorial* masterpiece that belongs in a museum of modern art. The *atelier* bows to you.",
    "Worshipful. {score} points of high-end rhythmic art. You’ve captured the soul of the Bunnester brand and given it a physical form. This silhouette is the gold standard, a masterpiece of *je ne sais quoi* that elevates the *lookbook* to a holy text. This is true Couture.",
    "I am actually speechless. {score} is the visual equivalent of a standing ovation from the gods of fashion. Your silhouette has achieved immortality, moving with an *editorial* grace that is both terrifying and beautiful. You are the architect of the Haute Couture future. Flawless.",
    "You are the silhouette that will define this era. {score}? This is your world; we just live in it. Every step was a poem, every note a heartbeat, every movement a testament to the power of the *atelier*. The editor-in-chief is crying. This is the pinnacle of *je ne sais quoi*.",
    "The front row is in shock. {score} is a performance that rendered the critics irrelevant. You have achieved a level of *editorial* perfection that defies description, a silhouette that is both raw and refined, industrial and divine. You are the ultimate Bunnester icon. Bravo!",
    "At {score}, you aren't just a player; you are the architect of the Haute Couture future. Your silhouette is a surgical strike on the concept of mediocrity, a brilliant display of *atelier* brilliance and *je ne sais quoi*. This is the moment fashion changed forever.",
    "You’ve done it. {score} is the zenith of the Bunnester aesthetic. I have nothing left to teach you. Your silhouette is a perfect expression of *je ne sais quoi*, an *editorial* miracle that will be spoken about in hushed tones at every atelier in Paris. You are a legend.",
    "Pure, unmitigated genius. {score} is a score that belongs in the stars. Your silhouette is a celestial event, a masterpiece of *avant-garde* couture that transcends the limits of time and space. The lookbook of the universe is yours to write. Divine.",
    "The static didn't stand a chance. At {score}, you were a god among mortals. Truly, the White Rabbit is yours to lead. Your silhouette is an *editorial* triumph of the highest order, a brilliant fusion of the *atelier* and the beat. Absolute perfection.",
    "If 'Haute Couture' had a physical form, it would be your walk at {score}. This is perfection in its highest form, a silhouette that is both a revolution and a homecoming. The *je ne sais quoi* is no longer a mystery; it is your name. Flawless.",
    "You didn't just win; you colonized the concept of rhythm. {score}? You are the gold standard now. Your silhouette is the blueprint for the future of fashion, an *editorial* victory that will inspire the *atelier* for generations. You are the icon.",
    "A {score} is a standing ovation from the gods of techno. Your silhouette has achieved immortality, moving with a *je ne sais quoi* that is both timeless and futuristic. This is the ultimate *editorial* achievement. The runway is yours forever.",
    "This is the pinnacle. {score} is a performance so sharp it could cut diamonds. The front row is yours, the *atelier* is yours, the world is yours. Your silhouette is a masterpiece of high-fashion intent and *je ne sais quoi*. Simply sublime.",
    "You have reached the horizon. {score} is the point where fashion meets divinity. I am humbled by your presence. Your silhouette is a prayer in motion, an *editorial* miracle that justifies every hour spent in the *atelier*. Absolute Couture.",
    "Legendary. {score} is a number that belongs in a museum of modern art. You have transcended the limits of the human form to become a pure expression of style. Your silhouette is the final word in the *editorial* history of the world. Bravo.",
    "At {score}, you are no longer a model; you are the Idea. The silhouette is perfect, the timing is absolute, the *je ne sais quoi* is universal. You have turned the *atelier* into a cathedral and the runway into a revelation. This is your coronation.",
    "A {score} is a supernova of style. You’ve delivered a silhouette that is so purely *editorial* it actually redefined the term. The *atelier* is no longer just a place; it's you. Absolute *je ne sais quoi*.",
    "At {score}, you are the master of the digital couture universe. Your silhouette is a flawlessly executed poem, a sharp *editorial* masterpiece that renders every other lookbook obsolete. Pure genius.",
    "A {score} is the sound of fashion finally finding its true purpose. You’ve achieved a silhouette of such staggering beauty and *avant-garde* intent that the *atelier* has reached its final form. Simply divine."
  ]
};

function getLocalReview(score: number): string {
  let tier: string;
  if (score < 150) tier = 'trash';
  else if (score < 450) tier = 'boring';
  else if (score < 900) tier = 'avantGarde';
  else tier = 'couture';

  const options = REVIEWS[tier];
  const index = Math.floor(Math.random() * options.length);
  return options[index].replace('{score}', score.toString());
}

/**
 * Returns a high-fashion performance review based on the score.
 * This function is now fully local and does not use the Gemini API.
 */
export async function getPerformanceReview(score: number): Promise<string> {
  // Simulate a slight delay for dramatic effect
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(getLocalReview(score));
    }, 1200);
  });
}
